<?php

namespace QwebCMS\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TblCatalogueProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblCatalogueProductRepository extends EntityRepository
{
    public function findAllFeatureByLanguage($id_language = null)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT p, f FROM QwebCMSCatalogoBundle:TblCatalogueProduct p JOIN p.featurevalues f WHERE f.idTblLingua = ?1 AND p.idTblLingua = ?1');
        $query->setParameter(1, $id_language);


        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
