_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
    
products:
    path:     /products
    defaults: { _controller: AcmeDemoBundle:Welcome:allProduct }
    
create_product:
    path:     /products/new
    defaults: { _controller: AcmeDemoBundle:Product:create }

show_product:
    path:     /product/show/{id}
    defaults: { _controller: AcmeDemoBundle:Product:show }

update_product:
    path:     /product/update/{id}
    defaults: { _controller: AcmeDemoBundle:Product:update }

delete_product:
    path:     /product/delete/{id}
    defaults: { _controller: AcmeDemoBundle:Product:delete }
    
categories:
    path:     /categories
    defaults: { _controller: AcmeDemoBundle:Welcome:allCategory }
    
create_category:
    path:     /categories/new
    defaults: { _controller: AcmeDemoBundle:Category:create }

show_category:
    path:     /category/show/{id}
    defaults: { _controller: AcmeDemoBundle:Category:show }

update_category:
    path:     /category/update/{id}
    defaults: { _controller: AcmeDemoBundle:Category:update }

delete_category:
    path:     /category/delete/{id}
    defaults: { _controller: AcmeDemoBundle:Category:delete }

features:
    path:     /features
    defaults: { _controller: AcmeDemoBundle:Welcome:allFeature }
    
create_features:
    path:     /features/new
    defaults: { _controller: AcmeDemoBundle:Feature:create }
    
show_features:
    path:     /feature/show/{id}
    defaults: { _controller: AcmeDemoBundle:Feature:show }
    
update_features:
    path:     /feature/update/{id}
    defaults: { _controller: AcmeDemoBundle:Feature:update }
    
delete_features:
    path:     /feature/delete/{id}
    defaults: { _controller: AcmeDemoBundle:Feature:delete }

featurevalues:
    path:     /featurevalues
    defaults: { _controller: AcmeDemoBundle:Welcome:allFeatureValue }
    
create_featurevalues:
    path:     /featurevalues/new
    defaults: { _controller: AcmeDemoBundle:Featurevalue:create }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
