imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form:
        resources:
            - 'IlClemeCatalogoBundle:Form:fields.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            # other form themes
            #- 'bootstrap_3_layout.html.twig'
            - 'VichUploaderBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    autenticatore_apikey:
        class:     IlCleme\CatalogoBundle\Security\ApiKeyAuthenticator
        arguments: ["@fornitore_utenti_apikey"]

oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone
            namer: custom_namer
            storage:
              directory:  'uploads/gallery'

        planimetrie:
            frontend: dropzone
            namer: custom_planimetrie_namer
            storage:
              directory:  'uploads/planimetrie'


liip_imagine:
    resolvers:
       default:
          web_path:

    # Questo è il resolver delle foto per portarle nella cartella pubblica del server,
    # al di fuori della radice di symfony
    #resolvers:
       #default:
          #web_path:
            #web_root: "%kernel.root_dir%/../../public"
            #cache_prefix: "catalogo"

    filter_sets:
        img_preview:
            quality: 100
            filters:
                thumbnail: { size: [196, 147], mode: outbound }
        img_small:
            quality: 70
            filters:
                thumbnail: { size: [550, 400], mode: outbound }
        img_medium:
            quality: 70
            filters:
                #relative_resize: { widen: 700 }
                thumbnail: { size: [878, 520], mode: outbound }
        img_large:
            quality: 70
            filters:
                #relative_resize: { widen: 1200 }
                #downscale: { max: [740, 500] }
                thumbnail: { size: [1280, 1024], mode: outbound }
        mini_img:
            quality: 100
            filters:
                relative_resize: { widen: 100 }
#            post_processors:
#                jpegoptim: {}


knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: ord       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig
        #filtration: KnpPaginatorBundle:Pagination:filtration.html.twig
        filtration: IlClemeCatalogoBundle:Welcome:filter.html.twig

vich_uploader:
    db_driver: orm

    mappings:
        featurevalues_image:
            uri_prefix:         /public/ico-caratteristiche
            upload_destination: %kernel.root_dir%/../web/public/ico-caratteristiche

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        allegati:
            uri_prefix:         /allegati
            upload_destination: %kernel.root_dir%/../web/allegati
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true


        logo:
            uri_prefix:         /logo
            upload_destination: %kernel.root_dir%/../web/logo
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true