qweb_cms_user:
    resource: "@IlClemeUserBundle/Resources/config/routing.yml"
    prefix:   /

qweb_cms_catalogo:
    resource: "@IlClemeCatalogoBundle/Resources/config/routing.yml"
    prefix:   /

oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"