# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    fornitore_utenti_apikey:
#        class: IlCleme\CatalogoBundle\Security\ApiKeyUserProvider

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  catalogobundle.upload_listener:
      class: IlCleme\CatalogoBundle\EventListener\UploadListener
      tags:
          - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
      arguments: ["@doctrine", "@service_container"]

  language.manager:
      class: IlCleme\CatalogoBundle\Services\LanguageManager
      arguments: ["@session"]
