<?php

namespace QwebCMS\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TblPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblPhotoRepository extends EntityRepository
{
}
