<?php

namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TblCatalogueProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblCatalogueProductRepository extends EntityRepository
{
}
