<?php

namespace IlCleme\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AllegatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllegatoRepository extends EntityRepository
{
}
