<?php

namespace IlCleme\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureRepository extends EntityRepository
{
    public function findFeaturesByLanguage($id_language)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT f FROM IlClemeCatalogoBundle:Feature f WHERE f.idTblLingua = ?1 ');
        $query->setParameters(array(
            1 => $id_language
        ));

        try{
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
