<?php

namespace IlCleme\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function countProduct($id_language = 4){
        $query = $this->getEntityManager()
            ->createQuery('SELECT COUNT (p.id) FROM IlClemeCatalogoBundle:Product p WHERE p.idTblLingua = ?1');
        $query->setParameters(array(
            1 => $id_language
        ));

        try {
            $count = $query->getSingleScalarResult();
            return $count;
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findFeaturevaluesProductByLanguage($id_product, $id_language = null)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT p, f FROM IlClemeCatalogoBundle:Product p JOIN p.featurevalues f WHERE f.idTblLingua = ?1 AND p.idTblLingua = ?1 AND p.id = ?2');
        $query->setParameters(array(
            1 => $id_language,
            2 => $id_product));

        try {
            $product = $query->getSingleResult();
            return $product->getFeaturevalues();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
