<?php

namespace IlCleme\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TblPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblPhotoRepository extends EntityRepository
{
    public function findLastPhotoByAlbum($id_album)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM IlClemeCatalogoBundle:TblPhoto p WHERE p.idTblPhotoCat = :id_album LIMIT 1 ORDER BY p.idTblPhoto ASC'
            )
            ->setParameter('id_album', $id_album)
            ->getResult();
    }
}
