services:
    fornitore_utenti_apikey:
        class: IlCleme\CatalogoBundle\Security\ApiKeyUserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]

    custom_namer:
        class: IlCleme\CatalogoBundle\Naming\NomeNamer
        arguments: [ "@doctrine.orm.entity_manager" ]

    custom_planimetrie_namer:
        class: IlCleme\CatalogoBundle\Naming\NomePlanimetrieNamer
        arguments: [ "@doctrine.orm.entity_manager" ]
