services:
    fornitore_utenti_apikey:
        class: QwebCMS\CatalogoBundle\Security\ApiKeyUserProvider
        arguments: [ @doctrine.orm.entity_manager ]

    custom_namer:
        class: QwebCMS\CatalogoBundle\Naming\NomeNamer
        arguments: [ @doctrine.orm.entity_manager ]

    custom_planimetrie_namer:
            class: QwebCMS\CatalogoBundle\Naming\NomePlanimetrieNamer
            arguments: [ @doctrine.orm.entity_manager ]