login_route:
    path:   /login
    defaults: { _controller: IlClemeUserBundle:Security:login }

login_check:
    path:   /login_check
    defaults: { _controller: IlClemeUserBundle:Security:loginCheck }

logout:
    path:   /logout

qweb_cms_user_homepage:
    path:     /admin/{name}
    defaults: { _controller: IlClemeUserBundle:Default:index }
